Repository ChoiGiSung/baseball, pull requests merged in 2021-05, with the labels that each got.

#2 [FE] 리액트 프로젝트 초기 구조 완성
  FE/.gitignore
  FE/.prettierrc
  FE/_noDel
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/components/utilComponent/Button.jsx
  FE/src/index.js
  FE/src/style/reset.css
Labels: FE, enhancement

#6 [FE] TeamScore Component 초기 버전 완성
  .DS_Store
  FE/public/images/background.jpg
  FE/src/App.js
  FE/src/components/teamScore/TeamScore.jsx
  FE/src/components/teamScore/scoreTable/ScoreTable.jsx
  FE/src/components/teamScore/turn/Turn.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/logo/Logo.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/desc/Desc.jsx
  FE/src/components/teamSelect/selectTemplate/select/Select.jsx
Labels: FE, enhancement

#7 [FE] TeamSelect Component 초기 버전 완성
  FE/src/App.js
  FE/src/common/reference.js
  FE/src/common/style/GlobalStyle.jsx
  FE/src/common/style/reset.css
  FE/src/common/style/theme.js
  FE/src/common/util.js
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/logo/Logo.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/desc/Desc.jsx
  FE/src/components/teamSelect/selectTemplate/select/Select.jsx
  FE/src/components/teamSelect/selectTemplate/selectItems/SelectGame.jsx
  FE/src/components/teamSelect/selectTemplate/selectItems/SelectGameItem.jsx
Labels: FE, enhancement

#13 [FE] GamePlay 컴포넌트 구조 설계 완료
  FE/src/App.js
  FE/src/common/style/GlobalStyle.jsx
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/PitchButton.jsx
  FE/src/components/gamePlay/battleGround/partial/Round.jsx
  FE/src/components/gamePlay/battleGround/partial/SBO.jsx
  FE/src/components/gamePlay/gameScore/GameScore.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreen.jsx
  FE/src/components/gamePlay/situationScreen/SituationScreen.jsx
  FE/src/components/gamePlay/situationScreen/situation/Situation.jsx
  FE/src/components/teamScore/TeamScore.jsx
  FE/src/components/teamScore/turn/Turn.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/logo/Logo.jsx
Labels: FE, design

#16 [BE] 기능 구현
  BE/.gitignore
  BE/_noDel
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/codesquad/coco/CocoApplication.java
  BE/src/main/java/com/codesquad/coco/game/GameController.java
  BE/src/main/java/com/codesquad/coco/game/GameService.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/GameDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/InningsDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/ScoreBoardDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/GameRepository.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/DTO/GamePlayDTO.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/DTO/GameScoreDTO.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/Game.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/Innings.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/ScoreBoard.java
  BE/src/main/java/com/codesquad/coco/player/PlayerController.java
  BE/src/main/java/com/codesquad/coco/player/PlayerService.java
  BE/src/main/java/com/codesquad/coco/player/domain/DTO/PlayerDTO.java
  BE/src/main/java/com/codesquad/coco/player/domain/DTO/PlayerEventDTO.java
  BE/src/main/java/com/codesquad/coco/player/domain/Player.java
  BE/src/main/java/com/codesquad/coco/player/domain/PlayerDAO.java
  BE/src/main/java/com/codesquad/coco/player/domain/Record.java
  BE/src/main/java/com/codesquad/coco/player/domain/RecordType.java
  BE/src/main/java/com/codesquad/coco/player/domain/UserType.java
  BE/src/main/java/com/codesquad/coco/team/TeamService.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/MainPageTeamDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/TeamChoiceDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/TeamDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/TeamNameDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/TeamPointDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/DTO/TeamScoreDTO.java
  BE/src/main/java/com/codesquad/coco/team/domain/Team.java
  BE/src/main/java/com/codesquad/coco/team/domain/TeamDAO.java
  BE/src/main/java/com/codesquad/coco/team/domain/TeamRepository.java
  BE/src/main/java/com/codesquad/coco/utils/DTOConverter.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/coco/GameTest.java
  BE/src/test/java/com/codesquad/coco/ScoreTest.java
  BE/src/test/java/com/codesquad/coco/TeamTest.java
Labels: BE

#18 Feature be/17
  BE/src/main/java/com/codesquad/coco/game/GameController.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/GameDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/InningsDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/ScoreBoardDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/ScoreBoard.java
  BE/src/main/java/com/codesquad/coco/player/domain/PlayerDAO.java
  BE/src/main/java/com/codesquad/coco/team/TeamService.java
  BE/src/main/java/com/codesquad/coco/team/domain/TeamDAO.java
  BE/src/main/java/com/codesquad/coco/utils/SQL.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/HomeAwayTeamNameMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/InningsMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/PlayerMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/ScoreBoardMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/TeamNameMapper.java
Labels: BE

#19 [FE] GamePlay - GameScore 컴포넌트 완성 (프로토타입)
  FE/src/App.js
  FE/src/common/style/theme.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/gameScore/GameScore.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/selectTemplate/desc/Desc.jsx
  FE/src/components/utilComponent/Logo.jsx
Labels: FE, enhancement

#20 [FE] GamePlay - MatchScreen 컴포넌트 완성 (프로토타입)
  FE/src/App.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreen.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreenPlayerInfo.jsx
Labels: FE, enhancement

#21 [FE] GamePlay - SituationScreen 컴포넌트 완성 (프로토타입) 및 전체 react-router-dom 적용
  FE/package.json
  FE/src/App.js
  FE/src/common/style/theme.js
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreenPlayerInfo.jsx
  FE/src/components/gamePlay/situationScreen/SituationScreen.jsx
  FE/src/components/gamePlay/situationScreen/situation/Situation.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationRecord.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationStatus.jsx
  FE/src/components/teamSelect/selectTemplate/selectItems/SelectGame.jsx
  FE/src/components/teamSelect/selectTemplate/selectItems/SelectGameItem.jsx
  FE/src/index.js
  FE/src/pages/GamePlayPage.jsx
  FE/src/pages/IntroPage.jsx
Labels: FE, enhancement

#23 [FE] 일부 폴더 구조 변경 (TeamScore, TeamSelect)
  FE/src/components/teamScore/TeamScore.jsx
  FE/src/components/teamScore/partial/ScoreTable.jsx
  FE/src/components/teamScore/partial/Turn.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/partial/Desc.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGame.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
Labels: FE, refactoring

#25 [FE] 전체적인 View 보정 및 리팩토링 & GamePlay 부분 전반적으로 수정
  FE/src/App.js
  FE/src/common/style/AppStyle.jsx
  FE/src/common/style/GlobalStyle.jsx
  FE/src/common/style/theme.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/gameScore/GameScore.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreen.jsx
  FE/src/components/gamePlay/situationScreen/SituationScreen.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationRecord.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
  FE/src/components/utilComponent/CommonStyledCSS.jsx
  FE/src/components/utilComponent/Logo.jsx
Labels: CSS, FE

#27 [FE] GamePlay - BattleGround 컴포넌트 완성 (프로토타입)
  FE/src/common/style/AppStyle.jsx
  FE/src/common/style/theme.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/BaseballStadium.jsx
  FE/src/components/gamePlay/battleGround/partial/PitchButton.jsx
  FE/src/components/gamePlay/battleGround/partial/Round.jsx
  FE/src/components/gamePlay/battleGround/partial/SBO.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationRecord.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
  FE/src/components/utilComponent/CommonStyledCSS.jsx
Labels: FE, enhancement

#31 Feature be/29
  BE/build.gradle
  BE/src/main/java/com/codesquad/coco/game/GameController.java
  BE/src/main/java/com/codesquad/coco/game/GameService.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/GameDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/InningsDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/DAO/ScoreBoardDAO.java
  BE/src/main/java/com/codesquad/coco/game/domain/model/ScoreBoard.java
  BE/src/main/java/com/codesquad/coco/player/domain/PlayerDAO.java
  BE/src/main/java/com/codesquad/coco/player/domain/model/Record.java
  BE/src/main/java/com/codesquad/coco/team/TeamService.java
  BE/src/main/java/com/codesquad/coco/team/domain/TeamDAO.java
  BE/src/main/java/com/codesquad/coco/utils/BASEBALL_SQL.kt
  BE/src/main/java/com/codesquad/coco/utils/SQL.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/PlayerMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/ScoreBoardMapper.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/coco/GameTest.java
  README.md
Labels: BE

#38 [FE] GamePlay BattleGround Animation 추가
  FE/package.json
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/BaseballStadium.jsx
  FE/src/components/gamePlay/battleGround/partial/Icon.jsx
  FE/src/components/gamePlay/battleGround/partial/PitchButton.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
Labels: FE

#39 [FE] PopupFrame 생성 및 TeamScorePopup (구 TeamScore) 컴포넌트 보정 완료
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/playerListPopup/PlayerListPopup.jsx
  FE/src/components/teamScorePopup/TeamScorePopup.jsx
  FE/src/components/teamScorePopup/partial/ScoreTable.jsx
  FE/src/components/teamScorePopup/partial/Turn.jsx
  FE/src/components/utilComponent/Button.jsx
  FE/src/components/utilComponent/OpacityBackground.jsx
  FE/src/components/utilComponent/popupFrame/PopupFrame.jsx
  FE/src/components/utilComponent/popupFrame/PopupFrameBackground.jsx
Labels: CSS, FE, enhancement

#42 [FE] TeamScorePopup & PlayerListPopup 팝업 애니메이션 적용 완료 및 일부 수정
  FE/src/App.js
  FE/src/common/style/AppStyle.jsx
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/playerListPopup/PlayerListPopup.jsx
  FE/src/components/teamScorePopup/TeamScorePopup.jsx
  FE/src/components/utilComponent/Background.jsx
  FE/src/components/utilComponent/CommonStyledCSS.jsx
  FE/src/components/utilComponent/MainFrame.jsx
  FE/src/components/utilComponent/context/GamePlayProvider.jsx
  FE/src/components/utilComponent/context/GlobalProvider.jsx
  FE/src/components/utilComponent/popupFrame/PopupFrame.jsx
  FE/src/pages/GamePlayPage.jsx
  FE/src/pages/IntroPage.jsx
Labels: FE, enhancement

#43 [FE] GamePlay를 구성하는 컴포넌트 API 조작 시작
  FE/notuse_jsconfig.json
  FE/src/App.js
  FE/src/components/auth/login.jsx
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/BaseballStadium.jsx
  FE/src/components/gamePlay/battleGround/partial/Icon.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/teamSelect/selectTemplate/partial/selectGame/SelectGameItem.jsx
  FE/src/components/utilComponent/context/GlobalProvider.jsx
  FE/src/components/utilComponent/modal/Modal.jsx
  FE/src/components/utilComponent/modal/ModalCloseButton.jsx
  FE/src/pages/IntroPage.jsx
Labels: FE, enhancement

#46 [FE] Oauth Login 구현
  FE/notuse_jsconfig.json
  FE/package.json
  FE/public/images/github.jpeg
  FE/src/components/auth/auth.js
  FE/src/components/auth/login.jsx
  FE/src/components/teamSelect/TeamSelect.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/utilComponent/context/GlobalProvider.jsx
  FE/src/config/authMethods.js
  FE/src/config/firebase-config.js
  FE/src/hooks/useFetch.jsx
  FE/src/setupProxy.js
Labels: FE

#47 [FE] table API 적용
  FE/jsconfig.json.bak
  FE/package.json
  FE/src/common/reference.js
  FE/src/common/util.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/gamePlay/battleGround/partial/BaseballStadium.jsx
  FE/src/components/gamePlay/battleGround/partial/Icon.jsx
  FE/src/components/gamePlay/battleGround/partial/PitchButton.jsx
  FE/src/components/gamePlay/battleGround/partial/Round.jsx
  FE/src/components/gamePlay/battleGround/partial/SBO.jsx
  FE/src/components/gamePlay/battleGround/partial/StadiumPlayers.jsx
  FE/src/components/gamePlay/gameScore/GameScore.jsx
  FE/src/components/gamePlay/gameScore/GameScoreStatus.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreen.jsx
  FE/src/components/gamePlay/matchScreen/MatchScreenPlayerInfo.jsx
  FE/src/components/gamePlay/situationScreen/SituationScreen.jsx
  FE/src/components/gamePlay/situationScreen/situation/Situation.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationRecord.jsx
  FE/src/components/gamePlay/situationScreen/situation/SituationStatus.jsx
  FE/src/components/playerListPopup/PlayerListPopup.jsx
  FE/src/components/playerListPopup/partial/ListTable.jsx
  FE/src/components/teamSelect/selectTemplate/SelectTemplate.jsx
  FE/src/components/utilComponent/Logo.jsx
  FE/src/components/utilComponent/context/GamePlayProvider.jsx
  FE/src/components/utilComponent/context/GlobalProvider.jsx
  FE/src/hooks/useFetch.jsx
  FE/src/setupProxy.js.bak
Labels: FE

#48 [FE] 데모 전 PR, 미완) 안타 or 아웃에 따라 PUT 요청, 점수판 관련 API 요청은 진행중
  FE/package.json
  FE/src/common/util.js
  FE/src/components/gamePlay/GamePlay.jsx
  FE/src/components/gamePlay/battleGround/BattleGround.jsx
  FE/src/components/teamScorePopup/TeamScorePopup.jsx
  FE/src/components/teamScorePopup/partial/ScoreTable.jsx
  FE/src/components/utilComponent/context/GamePlayProvider.jsx
  FE/src/hooks/useFetch.jsx
Labels: FE, enhancement

#49 Oauth 구현
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/com/codesquad/coco/WebConfig.java
  BE/src/main/java/com/codesquad/coco/global/CustomExceptionController.java
  BE/src/main/java/com/codesquad/coco/user/UserController.java
  BE/src/main/java/com/codesquad/coco/user/UserService.java
  BE/src/main/java/com/codesquad/coco/user/domain/User.java
  BE/src/main/java/com/codesquad/coco/user/domain/UserDao.java
  BE/src/main/java/com/codesquad/coco/utils/FindSecretServerKey.java
  BE/src/main/java/com/codesquad/coco/utils/GitURI.java
  BE/src/main/java/com/codesquad/coco/utils/SQL.java
  BE/src/main/java/com/codesquad/coco/utils/SecretServerKey.java
  BE/src/main/java/com/codesquad/coco/utils/USER_SQL.kt
  BE/src/main/java/com/codesquad/coco/utils/mapper/UserCountMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/UserMapper.java
  BE/src/main/java/com/codesquad/coco/utils/mapper/UserRefreshTokenMapper.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/com/codesquad/coco/GameTest.java
  BE/src/test/java/com/codesquad/coco/TeamTest.java
Labels: BE
